### ISSUE TITLE
运行错误Not a gzipped file (b've')

### ISSUE THREAD

**Issue by SolitaryAnimal** [miaoshouai/miaoshouai-assistant#18]
操作系统: OpenSUSE Tumbleweed

启动时出现错误, 以下是错误信息(用户名使用******代替):

```
Error executing callback ui_tabs_callback for /home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/main.py
Traceback (most recent call last):
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 1036, in my_model_set
    self.install_preset_models_if_needed(False)
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 739, in install_preset_models_if_needed
    content = decoder.read()
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/home/*******/anaconda3/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/*******/stable-diffusion-webui/modules/script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 33, in on_event_ui_tabs_opened
    self.create_subtab_model_management()
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 173, in create_subtab_model_management
    my_models = self.runtime.get_local_models('', my_model_type.value)
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 285, in get_local_models
    model_info = self.search_model_info(chkpt_info, mpath, model_type)
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 377, in search_model_info
    for model in self.my_model_set:
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 1046, in my_model_set
    self.refresh_all_models()
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 162, in refresh_all_models
    self.install_preset_models_if_needed(True)
  File "/home/*******/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 739, in install_preset_models_if_needed
    content = decoder.read()
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/home/*******/anaconda3/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/home/*******/anaconda3/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')
```

**Comment by miaoshouai** [comment]
updated. do an update or reinstall to get the fix.

**Comment by SolitaryAnimal** [comment]
插件运行正常, 十分感谢!
