### ISSUE TITLE
启动不能加载controlnet

### ISSUE THREAD

**Issue by mizhewei** [miaoshouai/miaoshouai-assistant#19]
File "/Users/xx/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 10, in <module>
    from scripts.logging import logger
ImportError: cannot import name 'logger' from 'scripts.logging' (/Users/xx/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/logging/__init__.py)
环境：webui包；ControlNET来自扩展界面下载；猫手根据教程安装

**Comment by miaoshouai** [comment]
最新版的喵手已经解决了这个问题

**Comment by mizhewei** [comment]
安装新版报错：Error running install.py for extension /Users/xxx/stable-diffusion-webui/extensions/miaoshouai-assistant.
Command: "/Users/xxx/stable-diffusion-webui/venv/bin/python3.10" "/Users/xxx/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py"
Error code: 1
stdout: Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132

stderr: Traceback (most recent call last):
  File "/Users/xxx/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py", line 30, in <module>
    install_preset_models_if_needed()
  File "/Users/xxx/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py", line 18, in install_preset_models_if_needed
    content = decoder.read()
  File "/Users/xxx/miniconda3/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/Users/xxxx/miniconda3/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/Users/xxx/miniconda3/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/Users/xxx/miniconda3/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

**Comment by mizhewei** [comment]
手工解压后又出现这个问题Error executing callback ui_tabs_callback for /Users/vespermee/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/main.py
Traceback (most recent call last):
  File "/Users/vespermee/stable-diffusion-webui/modules/script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/vespermee/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 33, in on_event_ui_tabs_opened
    self.create_subtab_model_management()
  File "/Users/vespermee/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 173, in create_subtab_model_management
    my_models = self.runtime.get_local_models('', my_model_type.value)
  File "/Users/vespermee/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 285, in get_local_models
    model_info = self.search_model_info(chkpt_info, mpath, model_type)
  File "/Users/vespermee/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_runtime.py", line 377, in search_model_info
    for model in self.my_model_set:

**Comment by mizhewei** [comment]
TypeError: 'NoneType' object is not iterable

**Comment by miaoshouai** [comment]
mac的系统？

**Comment by mizhewei** [comment]
是的

**Comment by miaoshouai** [comment]
updated. do an update or reinstall to get the fix.

**Comment by mizhewei** [comment]
assets文件夹为空

**Comment by miaoshouai** [comment]
尝试重新安装呢？
