### ISSUE TITLE
something was wrong!!!

### ISSUE THREAD

**Issue by chenjian27** [miaoshouai/miaoshouai-assistant#20]
Error running install.py for extension /Users/chenjianyin/stable-diffusion-webui/extensions/miaoshouai-assistant.
Command: "/Users/chenjianyin/stable-diffusion-webui/venv/bin/python3.10" "/Users/chenjianyin/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py"
Error code: 1
stdout: Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132

stderr: Traceback (most recent call last):
  File "/Users/chenjianyin/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py", line 30, in <module>
    install_preset_models_if_needed()
  File "/Users/chenjianyin/stable-diffusion-webui/extensions/miaoshouai-assistant/install.py", line 18, in install_preset_models_if_needed
    content = decoder.read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

**Comment by chenjian27** [comment]
macos m1 16G

**Comment by miaoshouai** [comment]
updated. do an update or reinstall to get the fix.

**Comment by triphop** [comment]
does the fix still exist? If not, we'll close this issue.
