### ISSUE TITLE
stderr: Traceback

### ISSUE THREAD

**Issue by Tobe2d** [miaoshouai/miaoshouai-assistant#21]
Any idea how to fix this?

```
stderr: Traceback (most recent call last):
  File "E:\Ai__Project\stable-diffusion-webui\extensions\miaoshouai-assistant\install.py", line 30, in <module>
    install_preset_models_if_needed()
  File "E:\Ai__Project\stable-diffusion-webui\extensions\miaoshouai-assistant\install.py", line 16, in install_preset_models_if_needed
    with gzip.open(gzip_file, "rb") as compressed_file:
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Ai__Project\\stable-diffusion-webui\\extensions\\miaoshouai-assistant\\assets\\civitai_models.json.gz'

```

**Comment by miaoshouai** [comment]
get the latest installation and it will help you to get rid of this error

**Comment by Tobe2d** [comment]
I did update the extention however it did not solve the issue ;-(

**Comment by triphop** [comment]
it FileNotFoundError does not matter here, the missing tarball files will be fetched via miaoshou's submodule.
