### ISSUE TITLE
启动时发现有大量错误

### ISSUE THREAD

**Issue by rock-xj** [miaoshouai/miaoshouai-assistant#25]
Exception importing api
No checkpoints found. When searching for checkpoints, looked at:
 - file D:\Ai-Paint\Stable-Diffusion-MF\model.ckpt
 - directory D:\Ai-Paint\Stable-Diffusion-MF\models\Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations. The program will exit.
Traceback (most recent call last):
  File "D:\Ai-Paint\Stable-Diffusion-MF\extensions\sd_dreambooth_extension\scripts\api.py", line 25, in <module>
    from dreambooth import shared
  File "D:\Ai-Paint\Stable-Diffusion-MF\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 434, in <module>
    is_auto = load_auto_settings()
  File "D:\Ai-Paint\Stable-Diffusion-MF\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
    sd_model = ws.sd_model
  File "D:\Ai-Paint\Stable-Diffusion-MF\modules\shared.py", line 716, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Ai-Paint\Stable-Diffusion-MF\modules\sd_models.py", line 422, in get_sd_model
    load_model()
  File "D:\Ai-Paint\Stable-Diffusion-MF\modules\sd_models.py", line 440, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "D:\Ai-Paint\Stable-Diffusion-MF\modules\sd_models.py", line 181, in select_checkpoint
    exit(1)
  File "D:\Ai-Paint\Stable-Diffusion-MF\Python3.10\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
No checkpoints found. When searching for checkpoints, looked at:
 - file D:\Ai-Paint\Stable-Diffusion-MF\model.ckpt
 - directory D:\Ai-Paint\Stable-Diffusion-MF\models\Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations. The program will exit.

另外不支持一些启动器，比如：魔法与巫术课程标准书籍，爱兔等，一应用共享文件，启动器就无法启动。但这个共享模型文件夹功能很好，很实用，希望大大能坚持更新，谢谢了。

**Comment by miaoshouai** [comment]
这些错误好像不是喵手插件的 看上去是因为文件夹没有模型导致的

**Comment by rock-xj** [comment]
有一个模型，是1.5官方的模型。我做过几次测试，如移去喵手插件，启动就无故障显示，

**Comment by triphop** [comment]
应该是在**D:\Ai-Paint\Stable-Diffusion-MF\models**下没有模型, 请确保在该目录下有可用的模型.
如果确信已经有了所需的模型, 那请列一下D:\Ai-Paint\Stable-Diffusion-MF\models目录都有哪些文件.
