### ISSUE TITLE
CivitAI models cant be loaded or downloaded

### ISSUE THREAD

**Issue by BurnedSpaghetti** [miaoshouai/miaoshouai-assistant#26]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-1.4.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-1.4.0\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 489, in get_model_info
    m_list = self.get_model_byid(mid, self.model_source)
  File "D:\stable-diffusion-webui-1.4.0\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 474, in get_model_byid
    if payload.get("success") is not None and not payload.get("success"):
AttributeError: 'str' object has no attribute 'get'
2023-07-01 13:01:46,647 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-07-01 13:01:46,650 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

When i click on a model in model management or model download with CivitAI as the source i get this error but no problems with any of the others sources

**Comment by miaoshouai** [comment]
couldn't repreduce. might be beacuase civitai was under maintaning at the time was using?
