### ISSUE TITLE
Cannot Install Extension

### ISSUE THREAD

**Issue by RaXorX** [miaoshouai/miaoshouai-assistant#28]
Let me know if I'm wrong in assuming the installation needs the assets from codings.net or not and whether the installation process downloads files from that place automatically - and is accessible for everyone.

My installation of this extension simply sits idly for 10 minutes and still failed to install. Since there are barely any logs for whatever's happening/downloading from extensions I can't say what's wrong. Those assets are accessible via wechat/tencent unless the extensions downloads them without such need.

**Comment by miaoshouai** [comment]
did you install from webui extensions?
depending on your Internet speed, assets is a package which is about 40M. If you go through the extension installation from webui, the entire repo is about 400M something and will automatically download assets for you

**Comment by RaXorX** [comment]
```
*** Error completing request
*** Arguments: ('https://github.com/miaoshouai/miaoshouai-assistant.git', ['ads', 'localization', 'installed'], 0, 'assis') {}
    Traceback (most recent call last):
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\objects\submodule\base.py", line 1240, in module
        repo = git.Repo(module_checkout_abspath)
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\repo\base.py", line 282, in __init__
        self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\repo\base.py", line 363, in common_dir
        raise InvalidGitRepositoryError()
    git.exc.InvalidGitRepositoryError

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\objects\submodule\base.py", line 608, in update
        mrepo = self.module()
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\util.py", line 144, in wrapper
        return func(self, *args, **kwargs)
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\objects\submodule\base.py", line 1245, in module
        raise InvalidGitRepositoryError("No valid repository at %s" % module_checkout_abspath) from e
    git.exc.InvalidGitRepositoryError: No valid repository at E:\AIs\stable-diffusion\tmp\miaoshouai-assistant\assets

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\AIs\stable-diffusion\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "E:\AIs\stable-diffusion\modules\ui_extensions.py", line 384, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "E:\AIs\stable-diffusion\modules\ui_extensions.py", line 357, in install_extension_from_url
        submodule.update()
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\objects\submodule\base.py", line 666, in update
        mrepo = self._clone_repo(
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\objects\submodule\base.py", line 301, in _clone_repo
        clone = git.Repo.clone_from(
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\repo\base.py", line 1308, in clone_from
        return cls._clone(
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\repo\base.py", line 1219, in _clone
        finalize_process(proc, stderr=stderr)
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\util.py", line 419, in finalize_process
        proc.wait(**kwargs)
      File "E:\AIs\stable-diffusion\venv\lib\site-packages\git\cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git clone -v -n --separate-git-dir=E:/AIs/stable-diffusion/tmp/miaoshouai-assistant/.git/modules/assets -- https://e.coding.net/miaoshouai/miaoshou-stable-diffusion-webui/assets.git E:\AIs\stable-diffusion\tmp\miaoshouai-assistant\assets
      stderr: 'Cloning into 'E:\AIs\stable-diffusion\tmp\miaoshouai-assistant\assets'...
    POST git-upload-pack (185 bytes)
    POST git-upload-pack (227 bytes)
    error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
    error: 5273 bytes of body are still expected
    fetch-pack: unexpected disconnect while reading sideband packet
    fatal: early EOF
    fatal: fetch-pack: invalid index-pack output
```
Finally had an error in console. And yes I installed from the webui itself.
