### ISSUE TITLE
after installing am getting this erorr 

### ISSUE THREAD

**Issue by MetexLab** [miaoshouai/miaoshouai-assistant#29]
---
*** API error: GET: http://52.54.1.173:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"}
    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 153, in exception_handling
        return await call_next(request)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 117, in log_and_time
        res: Response = await call_next(req)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      *** API error: GET: http://52.54.1.173:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"}
    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 153, in exception_handling
        return await call_next(request)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 117, in log_and_time
        res: Response = await call_next(req)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/gradio/routes.py", line 271, in api_info
        return gradio.blocks.get_api_info(config, serialize)  # type: ignore
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/gradio/blocks.py", line 504, in get_api_info
        serializer = serializing.COMPONENT_MAPPING[type]()
    KeyError: 'dataset'

---
*** API error: GET: http://52.54.1.173:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"}
    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 153, in exception_handling
        return await call_next(request)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/home/ec2-user/stable-diffusion-webui/modules/api/api.py", line 117, in log_and_time
        res: Response = await call_next(req)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/gradio/routes.py", line 271, in api_info
        return gradio.blocks.get_api_info(config, serialize)  # type: ignore
      File "/home/ec2-user/stable-diffusion-webui/venv/lib64/python3.9/site-packages/gradio/blocks.py", line 504, in get_api_info
        serializer = serializing.COMPONENT_MAPPING[type]()
    KeyError: 'dataset'

**Comment by miaoshouai** [comment]
are you using 1.5RC?
you need to switch gradio-client to 0.2.7
see this post: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855

**Comment by MetexLab** [comment]
The error message indicates that the issue is in the file msai_prelude.py at the line:

def ENV_EXCLUSION(self) -> list[str]:

So, you should add the import statement in the msai_prelude.py file. Here's how you can do it:

Open the msai_prelude.py file.
At the top of the file, add the following line:
python
Copy code
from typing import List
Then, change the line from:
python
Copy code
def ENV_EXCLUSION(self) -> list[str]:
to:

python
Copy code
def ENV_EXCLUSION(self) -> List[str]:
Please note that Python is case-sensitive, so make sure to use List with a capital 'L'.





we have fixed it with this

**Comment by MetexLab** [comment]
now we are getting this 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/dd036d5a-9d25-4d7a-be6d-f57027c69354)
when installing 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/e94f6614-0deb-4653-a39f-051c11aa4f16)

Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/main.py", line 4, in <module>
        from scripts.assistant.miaoshou import MiaoShouAssistant
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 12, in <module>
        from scripts.runtime.msai_prelude import MiaoshouPrelude
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/__init__.py", line 3, in <module>
        from . import msai_prelude as prelude
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_prelude.py", line 17, in <module>
        class MiaoshouPrelude(metaclass=MiaoshouSingleton):
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_prelude.py", line 116, in MiaoshouPrelude
        def ENV_EXCLUSION(self) -> list[str]:
    TypeError: 'type' object is not subscriptable

**Comment by MetexLab** [comment]
now we are getting this 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/dd036d5a-9d25-4d7a-be6d-f57027c69354)
when installing 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/e94f6614-0deb-4653-a39f-051c11aa4f16)

Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/main.py", line 4, in <module>
        from scripts.assistant.miaoshou import MiaoShouAssistant
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/assistant/miaoshou.py", line 12, in <module>
        from scripts.runtime.msai_prelude import MiaoshouPrelude
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/__init__.py", line 3, in <module>
        from . import msai_prelude as prelude
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_prelude.py", line 17, in <module>
        class MiaoshouPrelude(metaclass=MiaoshouSingleton):
      File "/home/ubuntu/stable-diffusion-webui/extensions/miaoshouai-assistant/scripts/runtime/msai_prelude.py", line 116, in MiaoshouPrelude
        def ENV_EXCLUSION(self) -> list[str]:
    TypeError: 'type' object is not subscriptable

**Comment by MetexLab** [comment]
The error message indicates that the issue is in the file msai_prelude.py at the line:

def ENV_EXCLUSION(self) -> list[str]:

So, you should add the import statement in the msai_prelude.py file. Here's how you can do it:

Open the msai_prelude.py file.
At the top of the file, add the following line:
python
Copy code
from typing import List
Then, change the line from:
python
Copy code
def ENV_EXCLUSION(self) -> list[str]:
to:

python
Copy code
def ENV_EXCLUSION(self) -> List[str]:
Please note that Python is case-sensitive, so make sure to use List with a capital 'L'.




fixed it with this 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/aca58b8d-9e5a-4142-bc9f-3e84ba5ab51e)

**Comment by MetexLab** [comment]
it's stucked here no progress aws ec2 server g4dnxlarge ubuntu 
![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/139757358/8e8d182e-2eb2-4e90-a184-cdb1c8a96de7)

**Comment by miaoshouai** [comment]
@MetexLab don't have the linux enviornment to test it out. do you see anything from the log file in the log directory?
