### ISSUE TITLE
Error - callback ui_tabs_callback

### ISSUE THREAD

**Issue by Tobe2d** [miaoshouai/miaoshouai-assistant#3]
I install the extention by cloning it like any other extention using the UI and when start  SD i get this error and it did not load into the UI:

```

Error executing callback ui_tabs_callback for E:\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\main.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "E:\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 31, in on_event_ui_tabs_opened
    self.create_subtab_boot_assistant()
  File "E:\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 42, in create_subtab_boot_assistant
    gpu, theme, port, chk_args, txt_args, webui_ver = self.runtime.get_default_args()
  File "E:\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 65, in get_default_args
    theme = [k for k, v in self.prelude.theme_setting.items() if v == arg][0]
IndexError: list index out of range
```

**Comment by miaoshouai** [comment]
try to do an update. just pushed a new version to resolve this problem.
