### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by StrangerGithuber** [miaoshouai/miaoshouai-assistant#43]
Hi,
I updated today the AUTOMATA1111 to the newest version and now this extension gives this error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 302, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "F:\Automatic1111-stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 573, in get_api_info
    if type in client_utils.SKIP_COMPONENTS:
AttributeError: module 'gradio_client.utils' has no attribute 'SKIP_COMPONENTS'
```

I deleted other extensions which I installed just left this one and even so doesn't help.

**Comment by miaoshouai** [comment]
just push an emergency update to fix this problem. update to the latest version to solve this error msg.

**Comment by StrangerGithuber** [comment]
Hmm now comes a noob question. How to do that?

**Comment by miaoshouai** [comment]
you can either do a git pull in the miaoshouai directory under extensions or use the update tab from the UI itself and then close the webui console to do a full restart

**Comment by MrX292** [comment]
the problem is back.
is there a reason for changing `gradio-client==0.5.0` back to `gradio_client==0.2.7`?

**Comment by miaoshouai** [comment]
> @miaoshouai @superag the problem is back. is there a reason for changing `gradio-client==0.5.0` back to `gradio_client==0.2.7`?

just it changed back. accidentally check in the wrong version.
