### ISSUE TITLE
Key error: 'dataset'

### ISSUE THREAD

**Issue by DuckersMcQuack** [miaoshouai/miaoshouai-assistant#47]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 25.2s (launcher: 8.6s, import torch: 3.3s, import gradio: 1.1s, setup paths: 0.6s, other imports: 0.7s, setup codeformer: 0.2s, list SD models: 0.2s, load scripts: 5.0s, create ui: 4.9s, gradio launch: 0.5s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\gradio\routes.py", line 271, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "G:\Stablediff\Automatic1111\webuiDuckers-july\venv\lib\site-packages\gradio\blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by miaoshouai** [comment]
try to update to 1.7

**Comment by generalk25** [comment]
I have the same error. Just installed from the main branch, so i assume it's 1.7

**Comment by miaoshouai** [comment]
what is the automatic1111version you are using?

**Comment by generalk25** [comment]
version: [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)  •  python: 3.11.2  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [1dccd17eca](https://google.com/search?q=1dccd17ecae0d58d906513b61b4943e60dd8834175a1e2921593dbfa8a222b5a)

**Comment by miaoshouai** [comment]
for versions before 1.6.0, set the gradio_client==0.5.0 to gradio_client==0.2.7. That should resolve the error message.

**Comment by generalk25** [comment]
This is my requirements.txt file



GitPython
Pillow
accelerate

basicsr
blendmodes
clean-fid
einops
gfpgan
gradio==3.32.0
inflection
jsonmerge
kornia
lark
numpy
omegaconf
open-clip-torch

piexif
psutil
pytorch_lightning
realesrgan
requests
resize-right

safetensors
scikit-image>=0.19
timm
tomesd
torch
torchdiffeq
torchsde
transformers==4.25.1

**Comment by miaoshouai** [comment]
> This is my requirements.txt file
> 
> GitPython Pillow accelerate
> 
> basicsr blendmodes clean-fid einops gfpgan gradio==3.32.0 inflection jsonmerge kornia lark numpy omegaconf open-clip-torch
> 
> piexif psutil pytorch_lightning realesrgan requests resize-right
> 
> safetensors scikit-image>=0.19 timm tomesd torch torchdiffeq torchsde transformers==4.25.1

not the requirement file for webui, but the requirement file in the extesnions/miaoshouai-assistant folder

**Comment by generalk25** [comment]
That fixed it, thanks.
