### ISSUE TITLE
getting errors in the webui and when just downloading

### ISSUE THREAD

**Issue by axelmizu** [miaoshouai/miaoshouai-assistant#55]
error Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -n --separate-git-dir=F:/Stable-diffusion/stable-diffusion-webui/extensions/miaoshouai-assistant/.git/modules/assets -- https://e.coding.net/miaoshouai/miaoshou-stable-diffusion-webui/assets.git F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\assets
  stderr: 'Cloning into 'F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\assets'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (277 bytes)
error: RPC failed; curl 52 Empty reply from server
fatal: expected 'packfile'
'
*** Error executing callback ui_tabs_callback for F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\main.py
    Traceback (most recent call last):
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 1245, in my_model_set
        self.install_preset_models_if_needed(False)
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 938, in install_preset_models_if_needed
        sub_repo = git.Repo(self.prelude.assets_folder)
      File "F:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 213, in __init__
        raise NoSuchPathError(epath)
    git.exc.NoSuchPathError: F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\assets

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\Stable-diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 34, in on_event_ui_tabs_opened
        self.create_subtab_model_management()
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 180, in create_subtab_model_management
        my_models = self.runtime.get_local_models('', my_model_type.value)
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 361, in get_local_models
        model_info = self.search_model_info(chkpt_info, mpath, model_type)
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 482, in search_model_info
        if self.my_model_set is None:
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 1255, in my_model_set
        self.refresh_all_models()
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 168, in refresh_all_models
        self.install_preset_models_if_needed(True)
      File "F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 938, in install_preset_models_if_needed
        sub_repo = git.Repo(self.prelude.assets_folder)
      File "F:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 213, in __init__
        raise NoSuchPathError(epath)
    git.exc.NoSuchPathError: F:\Stable-diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\assets

ddont know if this is a known issue but ive tried some fixes and getting the same issue where its not getting the data at all. i have no issue with my internet connection and other extensions are downloading just fine. any help would be great

**Comment by miaoshouai** [comment]
haven't encountered that problem before.
can you do just git clone https://e.coding.net/miaoshouai/miaoshou-stable-diffusion-webui/assets.git?
if that works, just clone the assets folder to the miaoshouai-assistant folder and it will do the same thing.

**Comment by axelmizu** [comment]
remote: Enumerating objects: 462, done.
remote: Counting objects: 100% (462/462), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 17 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

this is what happens when i do that

**Comment by axelmizu** [comment]
so was running it again and noticed this when after i installed it
Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132
Installing Miaoshou assistant requirement: gradio_client==0.5.0
Installing Miaoshou assistant requirement: requests==2.31.0
Installing Miaoshou assistant requirement: urllib3==2.0.6
Installing Miaoshou assistant requirement: tqdm==4.64.0
failed to find out civitai_models.json under assets directory
failed to find out liandange_models.json under assets directory
failed to find out gpt_index.json under assets directory

do i need those files for this to work?

**Comment by miaoshouai** [comment]
not sure if this post might help:
https://gist.github.com/enqtran/10e33674701967edd12c3cf224c835f8

if you still can't get it working, try use the release version

**Comment by axelmizu** [comment]
that like you sent didnt do anything but i downloaded the 1.8 zip and now is working. thank you so much for the help!!!

**Comment by mauricio-jpr** [comment]
> that like you sent didnt do anything but i downloaded the 1.8 zip and now is working. thank you so much for the help!!!

This works for me too
