### ISSUE TITLE
Assistant not working when having models in custom folder

### ISSUE THREAD

**Issue by abmereslo** [miaoshouai/miaoshouai-assistant#56]
As the title says,  The assistant is not working when having models in custom folder. It doesn't find a single one of them.

**Comment by abmereslo** [comment]
I was able to fix the problem by making a mkling /j and the folders.

But upon clicking on Download Cover for Listed Models, I get this:

` File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\extensions\miaoshouai-assistant-main\scripts\runtime\msai_runtime.py", line 399, in set_all_covers
    img_list, l1, htmlDetail, h2 = self.get_model_info(model)
ValueError: too many values to unpack (expected 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Abmereslo\Desktop\StableDiffusionWebUI\extensions\miaoshouai-assistant-main\scripts\runtime\msai_runtime.py", line 416, in set_all_covers
    print(model[1], cover_url, dst, str(e))
UnboundLocalError: local variable 'cover_url' referenced before assignment`

why does this happen?
