### ISSUE TITLE
TimeoutError: timed out on fresh install

### ISSUE THREAD

**Issue by johnbrownlow** [miaoshouai/miaoshouai-assistant#64]
See log. This disappears when I remove miaoshouai-assistant. Also, it goes through installing requirements on every run, which seems odd.

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132
Installing Miaoshou assistant requirement: gradio_client==0.5.0
Installing Miaoshou assistant requirement: requests==2.31.0
Installing Miaoshou assistant requirement: urllib3==2.0.6
Installing Miaoshou assistant requirement: tqdm==4.64.0
Launching Web UI with arguments: --xformers
Style database not found: C:\Users\johnbrownlow\Desktop\A1111\webui\styles.csv
logs_location: C:\Users\johnbrownlow\Desktop\A1111\webui\extensions\miaoshouai-assistant\logs
CivitAI Browser+: Aria2 RPC started
Loading weights [43a74d3b59] from C:\Users\johnbrownlow\Desktop\A1111\webui\models\Stable-diffusion\absolutereality_f16.safetensors
Creating model from config: C:\Users\johnbrownlow\Desktop\A1111\webui\configs\v1-inference.yaml
C:\Users\johnbrownlow\Desktop\A1111\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py:229: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  row.style(equal_height=True)
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johnbrownlow\Desktop\A1111\webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\johnbrownlow\Desktop\A1111\webui\launch.py", line 44, in main
    start()
  File "C:\Users\johnbrownlow\Desktop\A1111\webui\modules\launch_utils.py", line 464, in start
    webui.webui()
  File "C:\Users\johnbrownlow\Desktop\A1111\webui\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\gradio\blocks.py", line 1968, in launch
    and not networking.url_ok(self.local_url)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\gradio\networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\johnbrownlow\Desktop\A1111\system\python\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)
Applying attention optimization: xformers... done.
Model loaded in 16.6s (load weights from disk: 5.4s, create model: 8.5s, apply weights to model: 2.2s, calculate empty prompt: 0.2s).
Press any key to continue . . .
`

**Comment by miaoshouai** [comment]
should be solved, its much faster now
