### ISSUE TITLE
does not load images and prompts

### ISSUE THREAD

**Issue by xanax19** [miaoshouai/miaoshouai-assistant#66]
when I click on a cover image it gives me an error, both for the checkpoints downloaded manually and for those downloaded from the extension.
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 799, in update_cover_info
    if img['meta'] is not None and img['meta'] != '':
KeyError: 'meta'

**Comment by miaoshouai** [comment]
ok~ looks like civitai changed their data structure, update the extension to the latest model to sovle this model.

**Comment by xanax19** [comment]
Thank you. now works
