### ISSUE TITLE
cannot install automatically. Manual install yields this error

### ISSUE THREAD

**Issue by ziat007** [miaoshouai/miaoshouai-assistant#69]
Using WebUI Forge.

```
logs_location: D:\AI\Programs\stable-diffusion-webui-forge\extensions\miaoshouai-assistant-main\logs
*** Error loading script: main.py
    Traceback (most recent call last):
      File "D:\AI\Programs\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\Programs\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\Programs\stable-diffusion-webui-forge\extensions\miaoshouai-assistant-main\scripts\main.py", line 4, in <module>
        from scripts.assistant.miaoshou import MiaoShouAssistant
      File "D:\AI\Programs\stable-diffusion-webui-forge\extensions\miaoshouai-assistant-main\scripts\assistant\miaoshou.py", line 15, in <module>
        from scripts.runtime.msai_runtime import MiaoshouRuntime
      File "D:\AI\Programs\stable-diffusion-webui-forge\extensions\miaoshouai-assistant-main\scripts\runtime\msai_runtime.py", line 25, in <module>
        from bs4 import BeautifulSoup
    ModuleNotFoundError: No module named 'bs4'

```

**Comment by miaoshouai** [comment]
if you are installing that in Forge, you need to pip install BeautifulSoup for the it's python environment. if you are using the embeded python forge version, you need to do system\python\python.exe -m pip install BeautifulSoup to make sure it is installed on your local environment.

**Comment by miaoshouai** [comment]
use the forge version for forge webui
https://github.com/miaoshouai/miaoshouai-assistant-forge
