### ISSUE TITLE
助手提示我没有找到C-net1.1的链接？

### ISSUE THREAD

**Issue by MIkoshiPA** [miaoshouai/miaoshouai-assistant#7]
我把出错文本贴上来了，可以帮我一下吗？

Traceback (most recent call last):
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 670, in download_model
    self.downloader_manager.download(
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions\miaoshouai-assistant\scripts\download\msai_downloader_manager.py", line 190, in download
    resp = requests.get(source_url, stream=True)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\requests\sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "D:\aiHuihua\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '<img src="https://msdn.miaoshouai.com/msai/kt/ez/9900922.png" style="width:150px;">'
![{FQWBPJ1 4T{W36IZ}5Z$56](https://user-images.githubusercontent.com/130540066/236600611-2839c654-754b-4ace-a87d-3ec04e1d5eb9.png)

**Comment by miaoshouai** [comment]
刚刚有个fix解决了这个问题 更新一下看看是不是ok了

**Comment by MIkoshiPA** [comment]
感谢，已经解决了
