### ISSUE TITLE
Gradio component issue

### ISSUE THREAD

**Issue by warudokiruhya** [miaoshouai/miaoshouai-assistant#77]
Im trying to install it in forge and its impossible, it takes forever and each time it finishes it gives the same error, and I can only press a button to close everything. It forces me to uninstall the Miaoshou folder to be able to even start webui again.

`Installing requirements
Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132
Installing Miaoshou assistant requirement: gradio_client==0.5.0
Installing Miaoshou assistant requirement: requests==2.31.0
Installing Miaoshou assistant requirement: urllib3==2.0.6
Installing Miaoshou assistant requirement: tqdm==4.64.0
Launching Web UI with arguments:
Total VRAM 24564 MB, total RAM 65244 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Traceback (most recent call last):
  File "C:\Users\Ayu\Desktop\Forge2\webui\launch.py", line 54, in <module>
    main()
  File "C:\Users\Ayu\Desktop\Forge2\webui\launch.py", line 50, in main
    start()
  File "C:\Users\Ayu\Desktop\Forge2\webui\modules\launch_utils.py", line 546, in start
    import webui
  File "C:\Users\Ayu\Desktop\Forge2\webui\webui.py", line 17, in <module>
    initialize_forge()
  File "C:\Users\Ayu\Desktop\Forge2\webui\modules_forge\initialization.py", line 94, in initialize_forge
    import modules_forge.patch_basic
  File "C:\Users\Ayu\Desktop\Forge2\webui\modules_forge\patch_basic.py", line 6, in <module>
    import gradio.networking
  File "C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio\components\annotated_image.py", line 10, in <module>
    from gradio_client import handle_file
ImportError: cannot import name 'handle_file' from 'gradio_client' (C:\Users\Ayu\Desktop\Forge2\system\python\lib\site-packages\gradio_client\__init__.py)`

**Comment by miaoshouai** [comment]
please install the forge version from readme
