### ISSUE TITLE
An error appears when clearing vram

### ISSUE THREAD

**Issue by ghost** [miaoshouai/miaoshouai-assistant#78]
An error appears in the console when the vram is forced or automatically cleared. Tried without other extensions, venv cleared every time. I also tried reinstalling the extension itself. The sd version from a1111 is the latest. There are no errors when configuring venv. 
```Miaoshouai boot assistant: Memory Released!
Traceback (most recent call last):
  File "D:\NeuroTech\stable-diffusion-webui\venvWin\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\NeuroTech\stable-diffusion-webui\venvWin\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\NeuroTech\stable-diffusion-webui\venvWin\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\NeuroTech\stable-diffusion-webui\venvWin\lib\site-packages\gradio\components\markdown.py", line 73, in postprocess
    unindented_y = inspect.cleandoc(y)
  File "C:\Users\Shard\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 750, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'Markdown' object has no attribute 'expandtabs'

**Comment by HvTcCore** [comment]
The intended(?) solution: in the file "venv\lib\site-packages\gradio\components\markdown.py " change:
```
    def postprocess(self, y: str | None) -> str | None:
        """
        Parameters:
            y: markdown representation
        Returns:
            HTML rendering of markdown
        """
        if y is None:
            return None
        unindented_y = inspect.cleandoc(y)
        return unindented_y
```
to:
```
    def postprocess(self, y: str | None) -> str | None:
        """
        Parameters:
            y: markdown representation
        Returns:
            HTML rendering of markdown
        """
        if y is None:
            return None
        if not isinstance(y, str):
            y = str(y)
        unindented_y = inspect.cleandoc(y)
        return unindented_y

**Comment by zethriller** [comment]
Not sure if gradio or python lib issue for this one, but i don't think it's the extension.
I think it tries to update a gradio markdown label with this ?
Fixed (big word...) this here by patching inspect.py (`C:\Users\Shard\AppData\Local\Programs\Python\Python310\lib\inspect.py` with your paths)

Go to line 750 then edit the beginning of `cleandoc()`:

```python
def cleandoc(doc):
    """Clean up indentation from docstrings.

    Any whitespace that can be uniformly removed from the second line
    onwards is removed."""
    try:
        if doc.__class__.__name__ == 'Markdown': # if markdown passed to cleandoc, force convert to string before proceeding
            lines = str(doc).expandtabs().split('\n')
        else: # Normal case
            lines = doc.expandtabs().split('\n')
    except UnicodeError:
        return None
    else:
```

**Comment by HvTcCore** [comment]
It looks like it worked for me, but the cleanup notification is not displayed in the GUI, plus reinstalling python will require a fix again, so I fixed the extension itself:

\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py
Line 298+ (added "raise" to except):
```python
            print('Miaoshouai boot assistant: Memory Released!')
        except:
            print('Miaoshouai boot assistant: Memory Release Failed...!')
            raise
```
Line 316+ (added "return str(msg)"):
```python
            msg = 'Memory Released! (May not work if you already got CUDA out of memory error)'
            return str(msg)
        except Exception as e:
            msg = f'Memory Release Failed! ({str(e)})'
            return str(msg)
```
---
\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py
Line 138
```python
        reload_button.click(self.runtime.force_mem_release, outputs=[md_vram_release])
```
to
```python
        reload_button.click(self.runtime.force_mem_release, outputs=[md_vram_release]).then(lambda: gr.update(visible=True), outputs=[md_vram_release])
```
The solution is probably not perfect, but there's nothing I can do about it, and it works + the GUI notification has been fixed.
