### ISSUE TITLE
civitai api key - trying to save the key causes error

### ISSUE THREAD

**Issue by Symbiot78** [miaoshouai/miaoshouai-assistant#80]
when I copy paste the API key it throws an error in the ui.
in docker logs I see this:

2024-11-23 09:43:25,827 - _client.py [line:1729] - INFO: HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/opt/conda/lib/python3.10/site-packages/gradio/components/markdown.py", line 73, in postprocess
    unindented_y = inspect.cleandoc(y)
  File "/opt/conda/lib/python3.10/inspect.py", line 750, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'Markdown' object has no attribute 'expandtabs'
2024-11-23 09:44:31,545 - _client.py [line:1729] - INFO: HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2024-11-23 09:44:31,568 - _client.py [line:1729] - INFO: HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"

**Comment by Symbiot78** [comment]
it also seems if I change the VRAM size setting from CPU to something else and click apply it does say saved but if I reboot the container it is back to CPU.

**Comment by shipdocs** [comment]
i have the same initial error:
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/martin/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/martin/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/martin/.local/lib/python3.10/site-packages/gradio/components/markdown.py", line 73, in postprocess
    unindented_y = inspect.cleandoc(y)
  File "/usr/lib/python3.10/inspect.py", line 750, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'Markdown' object has no attribute 'expandtabs'

**Comment by ClonedBoy** [comment]
I got the error as well, but when I checked the file in configs/settings.json, the key was saved. It seems the script cannot validate. If it is not saved, you can add it manually to the file.
